### ISSUE TITLE
[WebApp] AutoLight 

### ISSUE THREAD

**Issue by Ankitpahuja** [CapstoneProject18/Automatic-Street-lighting-System#1]
As a legit user of Automate Street Lighting system, lets a user know about smart street lighting's system and file a complaint and for an admin to manage street light system.

This epic is created to set a base for complete application(WebApp). It includes following sub-modules:

- [Informational] Single Page Website 
- [UI/UX] Admin Login Page
- [UI/UX] For logged in users
- [Password Storage] Secure Login 
- [Nav] Light Control
- [Nav] Complaint System
- [Nav] Weather Prediction
- [Nav] Sign Out

**Comment by isha3026** [comment]
Do we need role based authentication for the web app?
