### ISSUE TITLE
Up-time/ down-time

### ISSUE THREAD

**Issue by isha3026** [CapstoneProject18/Automatic-Street-lighting-System#5]
As a logged-in user, I would be able to see the up-time/down-time for all the street lights in our system.

Acceptance criteria:
I intend to see a graph with (light-number) as x-axis and (up-time) as y-axis and also an average up-time/down-time with respect to time.
Note: By Up-time/down-time here means the time duration for which the lights are turned on/off.

**Comment by ayushigoel9** [comment]
Along with uptime and downtime of the current lights, the web app forecasts the downtime of the upcoming 7 street lights
